# This configuration file is created for the cycle branch

Main:
    event_queue_size: 4096

EventSinks:
    #- LogEventSink:
    #    class: "log_event_sink.LogEventSink"
    - MQTTPublisher:
        class: "mqtt_event_sink.MQTTEventSink"
        hostname: "iqueue.ics.uci.edu"
        #hostname: "dime.smartamerica.io"
        #hostname: "m2m.eclipse.org"
        hostport: 1883
        username: null
        password: null
        keepalive: 60
    - MySQLDatabase:
        class: "mysql_event_sink.MySQLEventSink"
        dbname: "scale_cycle"
        username: "scale_usr"
        password: "123456"
    - MySQLDatabaseClassified:
        class: "mysql_classified_event_sink.MySQLClassifiedEventSink"
        dbname: "scale_cycle"
        username: "scale_usr"
        password: "123456"
        event_types:
            - "location_update"
            - "iwlist_scan"

Applications:
    - LocationManager:
        class: "location_manager.LocationManager"
    - MySQLDatabase:
        class: "mysql_maintainer.MySQLMaintainer"
        dbname: "scale_cycle"
        username: "scale_usr"
        password: "123456"

Sensors:
    - HBSensor:
        class: "heartbeat_virtual_sensor.HeartbeatVirtualSensor"
        dev_name: "hb0"
        interval: 60
    #- PIRSensor:
    #    class: "pir_virtual_sensor.PIRVirtualSensor"
    #    dev_name: "pir0"
    #    gpio_pin: 17
    #- LightSensor:
    #    class: "light_virtual_sensor.LightVirtualSensor"
    #    dev_name: "light0"
    #    analog_port: 3
    #    threshold: 400
    #- GasSensor:
    #    class: "gas_virtual_sensor.GasVirtualSensor"
    #    dev_name: "gas0"
    #    analog_port: 0 
    #    threshold: 500
    #- RawAnalogSensor:
    #    class: "raw_analog_virtual_sensor.RawAnalogVirtualSensor"
    #    dev_name: "raw0"
    #    analog_port: 2
    #- GeoIPSensor:
    #    class: "location_sensors.geo_ip_virtual_sensor.GeoIPVirtualSensor"
    #    dev_name: "geoip0"
    - InternetAccessSensor:
        class: "internet_access_virtual_sensor.InternetAccessVirtualSensor"
        dev_name: "net0"
    - IWListSensor:
        class: "iwlist_virtual_sensor.IWListVirtualSensor"
        dev_name: "iw0"
        if_name: "wlan0"
    - GPSSensor:
        class: "location_sensors.gps_virtual_sensor.GPSVirtualSensor"
        dev_name: "gps0"

