# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geocron_header.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='geocron_header.proto',
  package='geocron_header',
  serialized_pb=_b('\n\x14geocron_header.proto\x12\x0egeocron_header\"s\n\rGeocronHeader\x12\x11\n\tm_forward\x18\x01 \x02(\x08\x12\x0f\n\x07m_nHops\x18\x02 \x02(\r\x12\r\n\x05m_seq\x18\x03 \x02(\r\x12\x0e\n\x06m_dest\x18\x04 \x02(\r\x12\x10\n\x08m_origin\x18\x05 \x02(\r\x12\r\n\x05m_ips\x18\x06 \x03(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GEOCRONHEADER = _descriptor.Descriptor(
  name='GeocronHeader',
  full_name='geocron_header.GeocronHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_forward', full_name='geocron_header.GeocronHeader.m_forward', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_nHops', full_name='geocron_header.GeocronHeader.m_nHops', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_seq', full_name='geocron_header.GeocronHeader.m_seq', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_dest', full_name='geocron_header.GeocronHeader.m_dest', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_origin', full_name='geocron_header.GeocronHeader.m_origin', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_ips', full_name='geocron_header.GeocronHeader.m_ips', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['GeocronHeader'] = _GEOCRONHEADER

GeocronHeader = _reflection.GeneratedProtocolMessageType('GeocronHeader', (_message.Message,), dict(
  DESCRIPTOR = _GEOCRONHEADER,
  __module__ = 'geocron_header_pb2'
  # @@protoc_insertion_point(class_scope:geocron_header.GeocronHeader)
  ))
_sym_db.RegisterMessage(GeocronHeader)


# @@protoc_insertion_point(module_scope)
