#! /bin/sh -e

#### BEGIN INIT INFO
# Provides:          CSN
# Required-Start:    $network $time $local_fs
# Required-Stop:     $network $time $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CSN client daemon
# Description:       Background daemon to poll CSN phidget 1056 device
### END INIT INFO

#
# Author:       Richard Guy <help@communityseismicnetwork.org>
#

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/local/sbin/csnd

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting CSN daemon" "csnd"
        start_daemon $DAEMON $1
        log_end_msg $?
    ;;

    stop)
        log_daemon_msg "Stopping CSN daemon" "csnd"
        $DAEMON $1
        log_end_msg $?
    ;;

    force-reload|restart)
        $0 stop
        $0 start
    ;;

    *)

    echo "Usage: /etc/init.d/csnd {start|stop|restart|force-reload}"

    exit 1
    ;;
esac
exit 0
