#!/bin/sh
### BEGIN INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="CSN Deamon"
NAME="csnd"
DAEMON="/usr/sbin/$NAME"
SCRIPTNAME=/etc/init.d/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

. /lib/lsb/init-functions

# Include csnd defaults if available.
test -f /etc/default/csnd  && . /etc/default/csnd

#
#       Function that starts the daemon/service.
#
d_start() {
    $DAEMON start
}

#
#       Function that stops the daemon/service.
#
d_stop() {
    $DAEMON stop
}

#
#       Function that reload the config file for the daemon/service.
#
d_reload() {
    d_stop
    d_start
}

d_restart() {
    $DAEMON restart
}

#
#       Function that check the status of the daemon/service.
#
d_status() {
    $DAEMON -c && echo "$DESC is running" || echo "$DESC is not running"
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        d_start
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        d_stop
        log_end_msg $?
        ;;
    reload|force-reload)
        log_daemon_msg "Reloading services for $DESC" "$NAME"
        d_reload
        log_end_msg $?
        ;;
    restart)
        log_daemon_msg "Restarting $DESC" "$NAME"
	d_restart
        log_end_msg $?
        ;;
    status)
        d_status
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|reload}" >&2
        exit 1
        ;;
esac

exit 0
