#!/bin/sh
### BEGIN INIT INFO
# Provides:          csnd
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the CSN daemon.
### END INIT INFO


# To install:
#     cp init.d-script /etc/init.d/csnd
#     update-rc.d csnd defaults


DAEMON=/usr/sbin/csnd
NAME=csnd
DESC="CSN daemon"
SCRIPTNAME=/etc/init.d/$NAME
PIDFILE=/var/run/CSNDaemon.pid

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" $NAME
    if start-stop-daemon --start --quiet --oknodo --exec $DAEMON $1;
    then log_end_msg 0 || true;
    else log_end_msg 1 || true;
    fi
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" $NAME
    start-stop-daemon --stop --exec $DAEMON $1
    log_end_msg 0
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop}" >&2
    exit 1
    ;;
esac

exit 0
