#!/bin/sh

### BEGIN INIT INFO
# Provides:          scale_daemon 
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Put a short description of the service here
# Description:       Put a long description of the service here
### END INIT INFO
#     update-rc.d scale defaults

PYTHON="`which python`"

# Change the next 3 lines to suit where you install your script and what you want to call it
#DIR=/usr/local/scale/scale_client/core
# scale-client has been successfully installed

DAEMON="$PYTHON"
DAEMON_OPTS="-m scale_client"

CONFIG_SPEC="/etc/scale/client/config.yml"

#PIP_LS=$(pip freeze)
#echo "$PIP_LS" | grep -q "scale\-client"

MODULE_TEST=$($PYTHON -c 'import scale_client; print scale_client.__name__')
echo "$MODULE_TEST" | grep -q "scale_client"
if [ $? -eq 0 ]; then # If module scale_client is found in pip list

MODULE_PATH=$($PYTHON -c 'import scale_client; import os; print os.path.dirname(scale_client.__file__)')
CONFIG_PATH="$MODULE_PATH/config"

#echo "MODULE_PATH=$MODULE_PATH"
#echo "CONFIG_PATH=$CONFIG_PATH"

if [ -e $CONFIG_SPEC ]; then
	DAEMON_OPTS="$DAEMON_OPTS --config $CONFIG_SPEC"
else
	if grep -q sheeva /etc/hostname; then #XXX
	DAEMON_OPTS="$DAEMON_OPTS --config $CONFIG_PATH/sheeva_config.yml"
	elif grep -q pi /etc/hostname; then
	DAEMON_OPTS="$DAEMON_OPTS --config $CONFIG_PATH/pi_config.yml"
	elif grep -q cycle /etc/hostname; then
	DAEMON_OPTS="$DAEMON_OPTS --config $CONFIG_PATH/cycle_config.yml"
	fi
fi

else exit 2; # If module scale_client is not found in pip list
fi

DAEMON_NAME=scale_daemon

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting SCALE client" "$DAEMON_NAME"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
	sleep 1
	do_status
  }
do_stop () {
    log_daemon_msg "Stopping SCALE client" "$DAEMON_NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
  }
do_status () {
    status_of_proc -p $PIDFILE $DAEMON "SCALE client" && exit 0 || exit $?
  }

case "$1" in
    start|stop|status)
            do_${1}
    ;;
    restart|reload|force-reload)
            do_stop
            do_start
    ;;
	*)
            echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
            exit 1
    ;;
esac
