# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='event.proto',
  package='saf',
  serialized_pb='\n\x0b\x65vent.proto\x12\x03saf\x1a\x0c\x63ommon.proto\"\x8f\x03\n\x0c\x45ventMessage\x12.\n\x10\x63lient_signature\x18\x01 \x01(\x0b\x32\x14.saf.ClientSignature\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12.\n\rlocation_type\x18\x04 \x01(\x0e\x32\x17.saf.LocationSourceType\x12,\n\x05\x65vent\x18\x05 \x01(\x0b\x32\x1d.saf.EventMessage.SensorEvent\x12\x35\n\x0eother_readings\x18\x06 \x03(\x0b\x32\x1d.saf.EventMessage.SensorEvent\x1a\x94\x01\n\x0bSensorEvent\x12\x11\n\tsensor_id\x18\x01 \x01(\x04\x12$\n\x0bsensor_type\x18\x02 \x01(\x0e\x32\x0f.saf.SensorType\x12\x14\n\x08readings\x18\x03 \x03(\x01\x42\x02\x10\x01\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x13\n\x0b\x65vent_count\x18\x05 \x01(\x05\x12\x13\n\x0btime_window\x18\x06 \x01(\x05\"3\n\rEventResponse\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.saf.StatusMessageB!\n\x18\x65\x64u.caltech.saf.messagesB\x05\x45vent')




_EVENTMESSAGE_SENSOREVENT = descriptor.Descriptor(
  name='SensorEvent',
  full_name='saf.EventMessage.SensorEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sensor_id', full_name='saf.EventMessage.SensorEvent.sensor_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sensor_type', full_name='saf.EventMessage.SensorEvent.sensor_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='readings', full_name='saf.EventMessage.SensorEvent.readings', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    descriptor.FieldDescriptor(
      name='date', full_name='saf.EventMessage.SensorEvent.date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_count', full_name='saf.EventMessage.SensorEvent.event_count', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time_window', full_name='saf.EventMessage.SensorEvent.time_window', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=286,
  serialized_end=434,
)

_EVENTMESSAGE = descriptor.Descriptor(
  name='EventMessage',
  full_name='saf.EventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='client_signature', full_name='saf.EventMessage.client_signature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='latitude', full_name='saf.EventMessage.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='longitude', full_name='saf.EventMessage.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='location_type', full_name='saf.EventMessage.location_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event', full_name='saf.EventMessage.event', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='other_readings', full_name='saf.EventMessage.other_readings', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EVENTMESSAGE_SENSOREVENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=434,
)


_EVENTRESPONSE = descriptor.Descriptor(
  name='EventResponse',
  full_name='saf.EventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='saf.EventResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=436,
  serialized_end=487,
)

import common_pb2

_EVENTMESSAGE_SENSOREVENT.fields_by_name['sensor_type'].enum_type = common_pb2._SENSORTYPE
_EVENTMESSAGE_SENSOREVENT.containing_type = _EVENTMESSAGE;
_EVENTMESSAGE.fields_by_name['client_signature'].message_type = common_pb2._CLIENTSIGNATURE
_EVENTMESSAGE.fields_by_name['location_type'].enum_type = common_pb2._LOCATIONSOURCETYPE
_EVENTMESSAGE.fields_by_name['event'].message_type = _EVENTMESSAGE_SENSOREVENT
_EVENTMESSAGE.fields_by_name['other_readings'].message_type = _EVENTMESSAGE_SENSOREVENT
_EVENTRESPONSE.fields_by_name['status'].message_type = common_pb2._STATUSMESSAGE

class EventMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class SensorEvent(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _EVENTMESSAGE_SENSOREVENT
    
    # @@protoc_insertion_point(class_scope:saf.EventMessage.SensorEvent)
  DESCRIPTOR = _EVENTMESSAGE
  
  # @@protoc_insertion_point(class_scope:saf.EventMessage)

class EventResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENTRESPONSE
  
  # @@protoc_insertion_point(class_scope:saf.EventResponse)

# @@protoc_insertion_point(module_scope)
